(function() {

  rap.registerTypeHandler( "clientData.Movies", {

    factory : function() {
      return movies;
    }

  } );

var movies = [
  "Above the Rim",
  "A Bug's Life",
  "Ace Ventura series:",
  "Ace Ventura: Pet Detective",
  "Ace Ventura: When Nature Calls",
  "Addams Family series:",
  "The Addams Family",
  "Addams Family Values",
  "Addicted to Love",
  "Adventures in Dinosaur City",
  "The Adventures of Elmo in Grouchland",
  "The Adventures of Ford Fairlane",
  "The Adventures of Huck Finn",
  "The Adventures of Priscilla: Queen of the Desert",
  "Affliction",
  "After Life",
  "The Age of Innocence",
  "Aimée and Jaguar",
  "Air Bud series:",
  "Air Bud",
  "Air Bud: Golden Receiver",
  "Air Force One",
  "Airborne",
  "Airheads",
  "Aladdin series:",
  "Aladdin",
  "Aladdin: The Return of Jafar",
  "Aladdin and the King of Thieves",
  "An Alan Smithee Film: Burn Hollywood Burn",
  "Alien 3",
  "Alien Resurrection",
  "Alive",
  "All Dogs Go to Heaven 2",
  "All Over Me",
  "Almost Heroes",
  "American Beauty",
  "American History X",
  "American Me",
  "American Movie",
  "American Pie",
  "The American President",
  "An American Tail: Fievel Goes West",
  "An American Tail: The Treasure of Manhattan Island",
  "Anaconda",
  "Analyze This",
  "Anastasia",
  "Andre",
  "Angela's Ashes",
  "Angels & Insects",
  "Angels in the Outfield",
  "Anglo-Saxon Attitudes",
  "Angus",
  "Animal Farm",
  "Another 48 Hours",
  "Another Stakeout",
  "Another Woman",
  "Antz",
  "Apollo 13",
  "Apt Pupil",
  "Arachnophobia",
  "Arcade",
  "Arizona Dream",
  "Armageddon",
  "Army of Darkness",
  "Art Museum by the Zoo",
  "As Good as It Gets",
  "Ashes of Time",
  "Assassins",
  "The Astronaut's Wife",
  "Austin Powers: International Man of Mystery",
  "Austin Powers: The Spy Who Shagged Me",
  "The Avengers",
  "Awakenings",
  "Babe",
  "Babe: Pig in the City",
  "Baby Geniuses",
  "Baby's Day Out",
  "The Bachelor",
  "Backbeat",
  "Backdraft",
  "Back to the Future Part III",
  "Bad Boys",
  "Bad Moon",
  "Balto",
  "Baraka",
  "Barb Wire",
  "Bartok the Magnificent",
  "Barton Fink",
  "BASEketball",
  "Basic Instinct",
  "Basquiat",
  "The Basketball Diaries",
  "Batman & Robin",
  "Batman Forever",
  "Batman: Mask of the Phantasm",
  "Batman Returns",
  "Bean",
  "The Beast",
  "The Beautician and the Beast",
  "Beauty and the Beast series:",
  "Beauty and the Beast",
  "Beauty and the Beast: The Enchanted Christmas",
  "Beauty and the Beast: Belle's Magical World",
  "Beauty and the Beast",
  "Beavis and Butt-head Do America",
  "Before Sunrise",
  "Being Human",
  "Benny & Joon",
  "Betsy's Wedding",
  "Better Than Chocolate",
  "The Beverly Hillbillies",
  "Beverly Hills Ninja",
  "Bicentennial Man",
  "Big Bully",
  "Big Daddy",
  "The Big Green",
  "The Big Lebowski",
  "Bill & Ted's Bogus Journey",
  "Billboard Dad",
  "Billy Madison",
  "Bio-Dome",
  "Bitter Moon",
  "Bird on a Wire",
  "The Birdcage",
  "The Birds II: Land's End",
  "Black Sheep",
  "Blade",
  "The Blair Witch Project",
  "Blank Check",
  "Blankman",
  "Blast from the Past",
  "Blue Chips",
  "Blue Streak",
  "The Bodyguard",
  "Body of Evidence",
  "Boiling Point",
  "The Bonfire of the Vanities",
  "Bongwater",
  "Boogie Nights",
  "The Boondock Saints",
  "Booty Call",
  "Bordello of Blood",
  "Born Yesterday",
  "Bottle Rocket",
  "Bound",
  "Bowfinger",
  "Boxing Helena",
  "Boys Don't Cry",
  "Boys on the Side",
  "Boyz n the Hood",
  "The Brady Bunch Movie",
  "Brain Candy",
  "Braindead",
  "Bram Stoker's Dracula",
  "Brassed Off",
  "The Brave",
  "Braveheart",
  "Bride of Re-Animator",
  "Bride of Chucky",
  "The Bridges of Madison County",
  "Bringing Out the Dead",
  "Brokedown Palace",
  "Broken Arrow",
  "A Bucket of Blood",
  "Bugged!",
  "Bugsy",
  "A Bug's Life",
  "Bulletproof",
  "Bullets Over Broadway",
  "Bulworth",
  "But I'm a Cheerleader",
  "Butch Camp",
  "Cabin Boy",
  "The Cable Guy",
  "Cadillac Man",
  "Camp Nowhere",
  "Camping Cosmos",
  "Cannibal! The Musical",
  "Cape Fear",
  "Captain America",
  "Carlito's Way",
  "Casino",
  "Carpool",
  "Casper series:",
  "Casper",
  "Casper: A Spirited Beginning",
  "Casper Meets Wendy",
  "Chain Reaction",
  "Chaplin",
  "Chasing Amy",
  "Child's Play 2",
  "Child's Play 3",
  "Chopper Chicks in Zombietown",
  "Christopher Columbus: The Discovery",
  "Chungking Express",
  "The Cider House Rules",
  "City Hall",
  "City of Angels",
  "City Slickers",
  "City Slickers 2: The Legend of Curly's Gold",
  "Class Act",
  "Class Action",
  "Class of Nuke 'Em High 2: Subhumanoid Meltdown",
  "Class of Nuke 'Em High 3: The Good, the Bad and the Subhumanoid",
  "Clear and Present Danger",
  "Clerks",
  "The Client",
  "Cliffhanger",
  "Clueless",
  "The Commitments",
  "Cobb",
  "Color of a Brisk and Leaping Day",
  "Color of Night",
  "Come See The Paradise",
  "Con Air",
  "Coneheads",
  "Congo",
  "Consenting Adults",
  "Conspiracy Theory",
  "Contact",
  "Cool As Ice",
  "Cool Runnings",
  "Cool World",
  "Cop and a Half",
  "Copycat",
  "Courage Under Fire",
  "Coven",
  "The Cowboy Way",
  "The Craft",
  "Crash",
  "Crazy in Alabama",
  "Crazy People",
  "Crimson Tide",
  "Cronos",
  "The Crow",
  "The Crucible",
  "Cruel Intentions",
  "The Crush",
  "Cry-Baby",
  "The Crying Game",
  "Cube",
  "Curse of the Puppet Master",
  "Cutthroat Island",
  "Cyrano de Bergerac",
  "Dances with Wolves",
  "Dante's Peak",
  "Dark City",
  "Darkman",
  "Darkman II: The Return of Durant",
  "Darkman III: Die Darkman Die",
  "Daylight",
  "Days of Being Wild",
  "Days of Thunder",
  "Dazed and Confused",
  "Dead Man on Campus",
  "Dead Man Walking",
  "Dead Presidents",
  "Dear God",
  "Death Becomes Her",
  "Deep Blue Sea",
  "Deep Impact",
  "Deep Rising",
  "Def by Temptation",
  "Defending Your Life",
  "Delicatessen",
  "Delta Force 2",
  "Demolition Man",
  "Demon Knight",
  "Dennis the Menace",
  "The Dentist",
  "The Dentist 2",
  "Desperado",
  "Deterrence",
  "Deuce Bigalow: Male Gigolo",
  "The Devil's Advocate",
  "The Devil's Own",
  "Dexter's Laboratory: Ego Trip",
  "Dick Tracy",
  "Die Hard 2",
  "Die Hard with a Vengeance",
  "Different Strokes",
  "Dirty Work",
  "Disclosure",
  "Disturbing Behavior",
  "Doc Hollywood",
  "Dog Park",
  "Dog Years",
  "Dogma",
  "Don Juan DeMarco",
  "Donnie Brasco",
  "Don't Be a Menace to South Central While Drinking Your Juice in the Hood",
  "The Doors",
  "Double, Double, Toil and Trouble",
  "Double Dragon",
  "Double Impact",
  "Double Jeopardy",
  "The Double Life of Véronique",
  "Double Team",
  "Doug's 1st Movie",
  "Down in the Delta",
  "Dr. Dolittle",
  "Dr. Giggles",
  "Dr. Jekyll and Ms. Hyde",
  "Dracula: Dead and Loving It",
  "Dragon Ball series",
  "Dragon Ball Z: The World's Strongest",
  "Dragon Ball Z: The Tree of Might",
  "Dragon Ball Z: Bardock – The Father of Goku",
  "Dragon Ball Z: Lord Slug",
  "Dragon Ball Z: Cooler's Revenge",
  "Dragon Ball Z: The Return of Cooler",
  "Dragon Ball Z: Super Android 13!",
  "Dragon Ball Z: The History of Trunks",
  "Dragon Ball Z: Broly – The Legendary Super Saiyan",
  "Dragon Ball Z: Bojack Unbound",
  "Dragon Ball Z Side Story: Plan to Eradicate the Saiyans",
  "Dragon Ball Z: Broly – Second Coming",
  "Dragon Ball Z: Bio-Broly",
  "Dragon Ball Z: Fusion Reborn",
  "Dragon Ball Z: Wrath of the Dragon",
  "Dragon Ball: The Path to Power",
  "Dragon Ball GT: A Hero's Legacy",
  "Dragonheart",
  "Drop Dead Fred",
  "Drop Zone",
  "DuckTales the Movie: Treasure of the Lost Lamp",
  "Dumb and Dumber",
  "Dunston Checks In",
  "Dying Young",
  "East is East",
  "Ed",
  "Ed Wood",
  "Edtv",
  "Edward Scissorhands",
  "Elizabeth",
  "Empire Records",
  "Los Enchiladas!",
  "Encino Man",
  "The End of Innocence",
  "The English Patient",
  "The Englishman Who Went Up a Hill But Came Down a Mountain",
  "Entrapment",
  "Eraser",
  "Ernest Goes to Jail",
  "Ernest Goes to School",
  "Eternity and a Day",
  "Europa Europa",
  "Even Cowgirls Get the Blues",
  "Event Horizon",
  "Ever After",
  "Everest",
  "Everyone Says I Love You",
  "Evita",
  "Eye for an Eye",
  "Eyes Wide Shut",
  "The Ex",
  "Executive Decision",
  "eXistenZ",
  "Exit to Eden",
  "The Exorcist III",
  "Face/Off",
  "Faces of Death IV",
  "Faces of Death V",
  "Faces of Death VI",
  "The Faculty",
  "Fair Game",
  "FairyTale: A True Story",
  "Fallen",
  "Fallen Angels",
  "Falling Down",
  "Fantasia 2000",
  "The Fantastic Four",
  "Fargo",
  "Far and Away",
  "Far Out Man",
  "Fatal Instinct",
  "Fathers' Day",
  "Faust",
  "Fear",
  "Fear of a Black Hat",
  "Fear and Loathing in Las Vegas",
  "Fearless",
  "Feeling Minnesota",
  "FernGully: The Last Rainforest",
  "FernGully 2: The Magical Rescue",
  "A Few Good Men",
  "The Fifth Element",
  "Fight Club",
  "Final Analysis",
  "Fire Down Below",
  "The Firm",
  "First Daughter",
  "First Kid",
  "The First Wives Club",
  "The Fisher King",
  "Flashback",
  "Flatliners",
  "The Flintstones",
  "Flirting with Disaster",
  "Flubber",
  "Fly Away Home",
  "Folks!",
  "For Richer or Poorer",
  "For the Boys",
  "Forgotten Silver",
  "Forrest Gump",
  "Four Rooms",
  "Four Weddings and a Funeral",
  "The Fox with Nine Tails",
  "Frankie and Johnny",
  "Freddy's Dead: The Final Nightmare",
  "Freejack",
  "Free Willy",
  "Free Willy 2: The Adventure Home",
  "Free Willy 3: The Rescue",
  "French Kiss",
  "The Freshman",
  "Fried Green Tomatoes",
  "The Frighteners",
  "From Dusk till Dawn",
  "From Dusk Till Dawn 2: Texas Blood Money",
  "The Fugitive",
  "Galaxy Quest",
  "Gang in Blue",
  "George of the Jungle",
  "Get Shorty",
  "The Getaway",
  "Getting Even with Dad",
  "Getting Lucky",
  "Gettysburg",
  "Ghost",
  "Ghost Dog: The Way of the Samurai",
  "Ghost in the Machine",
  "Ghosts of Mississippi",
  "G.I. Jane",
  "Gia",
  "Girl, Interrupted",
  "Girl 6",
  "Gloria",
  "The Godfather Part III",
  "Godzilla",
  "Godzilla 2000: Millennium",
  "Godzilla vs Destroyah",
  "Godzilla vs King Ghidorah",
  "Godzilla vs Mechagodzilla II",
  "Godzilla vs Mothra",
  "Godzilla vs SpaceGodzilla",
  "GoldenEye",
  "Good Burger",
  "Goodfellas",
  "The Good Son",
  "Good Will Hunting",
  "A Goofy Movie",
  "Grand Canyon",
  "Grass",
  "Great Expectations",
  "The Green Mile",
  "Gremlins 2: The New Batch",
  "The Grifters",
  "Grosse Pointe Blank",
  "Groundhog Day",
  "Grumpier Old Men",
  "Grumpy Old Men",
  "The Guardian",
  "Guest House Paradiso",
  "Guilty as Sin",
  "The Gun in Betty Lou's Handbag",
  "Gumby: The Movie",
  "Hackers",
  "Half Baked",
  "Halloween series:",
  "Halloween: The Curse of Michael Myers",
  "Halloween H20: 20 Years Later",
  "Hamlet",
  "The Hand That Rocks the Cradle",
  "Happy Gilmore",
  "Happy Together",
  "Hard Rain",
  "Hard Target",
  "Hard to Kill",
  "The Hard Way",
  "The Harmonium in My Memory",
  "The Haunting",
  "Havana",
  "He Got Game",
  "Heat",
  "Heaven and Earth",
  "Heavenly Creatures",
  "Heavyweights",
  "Hellraiser series:",
  "Hellraiser III: Hell on Earth",
  "Hellraiser: Bloodline",
  "Henry & June",
  "Hercules",
  "Hero",
  "Hey Tony! What's the Story?",
  "Higher Learning",
  "Highlander II: The Quickening",
  "Highlander III: The Final Dimension",
  "The Hills Have Eyes III",
  "Hocus Pocus",
  "Hoffa",
  "Home Alone series:",
  "Home Alone",
  "Home Alone 2: Lost in New York",
  "Home Alone 3",
  "Home Fries",
  "Homicide",
  "Honeymoon in Vegas",
  "Honey, I Blew Up the Kid",
  "Honey, We Shrunk Ourselves",
  "Hook",
  "Hoop Dreams",
  "Hope Floats",
  "Hot Shots!",
  "Hot Shots! Part Deux",
  "House on Haunted Hill",
  "House Party series:",
  "House Party",
  "House Party 2",
  "House Party 3",
  "Houseguest",
  "Housesitter",
  "How Stella Got Her Groove Back",
  "How the West Was Fun",
  "Howards End",
  "Hudson Hawk",
  "Hush",
  "The Hudsucker Proxy",
  "The Hunchback of Notre Dame",
  "Hurricane Streets",
  "Husbands and Wives",
  "I Know What You Did Last Summer",
  "I Like You, I Like You Very Much",
  "I Married a Strange Person!",
  "I Shot Andy Warhol",
  "I Still Know What You Did Last Summer",
  "I'll Be Home for Christmas",
  "The Ice Storm",
  "Identity Pieces",
  "The Idiots",
  "Idle Hands",
  "If the Sun Rises in the West",
  "In the Army Now",
  "In the Line of Fire",
  "In the Mouth of Madness",
  "In the Name of the Father",
  "Indecent Proposal",
  "Independence Day",
  "The Insider",
  "Inspector Gadget",
  "Intersection",
  "Interview with the Vampire",
  "Into Thin Air",
  "The Iron Giant",
  "The Island of Dr. Moreau",
  "It's Pat",
  "It Could Happen to You",
  "It Takes Two",
  "I.Q.",
  "Jack",
  "Jack Frost",
  "Jack Frost",
  "Jackie Brown",
  "Jacob's Ladder",
  "Jade",
  "James and the Giant Peach",
  "Jason's Lyric",
  "Jawbreaker",
  "Jefftowne",
  "Jerry Maguire",
  "Jetsons: The Movie",
  "JFK",
  "Jimmy Hollywood",
  "Jingle All the Way",
  "Joe's Apartment",
  "Johnny Mnemonic",
  "The Joy Luck Club",
  "Jude",
  "Judge Dredd",
  "Judgment Night",
  "Jumanji",
  "Jungle 2 Jungle",
  "Jungle Fever",
  "Junior",
  "Jurassic Park",
  "Jury Duty",
  "The Juror",
  "K2",
  "Kalifornia",
  "Kazaam",
  "The Kid",
  "Kids",
  "Killer Tomatoes Strike Back",
  "Kindergarten Cop",
  "The King and I",
  "King of New York",
  "Kingpin",
  "A Kiss Before Dying",
  "Kiss of Death",
  "Kuffs",
  "L.A. Confidential",
  "The Land Before Time series:",
  "The Land Before Time II: The Great Valley Adventure",
  "The Land Before Time III: The Time of the Great Giving",
  "The Land Before Time IV: Journey Through the Mists",
  "The Land Before Time V: The Mysterious Island",
  "The Land Before Time VI: The Secret of Saurus Rock",
  "The Land Girls",
  "Last Action Hero",
  "The Last Boy Scout",
  "Last Exit to Brooklyn",
  "Last Night",
  "Last of the Dogmen",
  "The Last of the Mohicans",
  "The Last Seduction",
  "A League of Their Own",
  "Leave It to Beaver",
  "Leaving Las Vegas",
  "Lethal Weapon 3",
  "Lethal Weapon 4",
  "Liar Liar",
  "Lies",
  "The Limey",
  "The Lion King series:",
  "The Lion King",
  "The Lion King II: Simba's Pride",
  "Lionheart",
  "Little Buddha",
  "Little Dieter Needs to Fly",
  "The Little Mermaid",
  "A Little Princess",
  "The Little Rascals",
  "Little Voice",
  "Little Women",
  "Live Wire",
  "Loch Ness",
  "Lock, Stock and Two Smoking Barrels",
  "Lone Star",
  "Longtime Companion",
  "Look Who's Talking Now",
  "Look Who's Talking Too",
  "Lord of the Flies",
  "Lost Highway",
  "Lost in Space",
  "The Lost World: Jurassic Park",
  "Love Jones",
  "Love Potion No. 9",
  "A Low Down Dirty Shame",
  "M. Butterfly",
  "Maborosi",
  "Mack the Knife",
  "Made in America",
  "Madeline",
  "Magnolia",
  "Major League series:",
  "Major League II",
  "Major League: Back to the Minors",
  "Malcolm X",
  "Malice",
  "Mallrats",
  "Man's Best Friend",
  "A Man Called Sarge",
  "The Man in the Iron Mask",
  "The Man Who Knew Too Little",
  "The Man Without a Face",
  "Man of the House",
  "Man on the Moon",
  "Margaret's Museum",
  "El Mariachi",
  "Marked for Death",
  "The Marrying Man",
  "Mars Attacks!",
  "Mary Reilly",
  "Mary Shelley's Frankenstein",
  "The Mask",
  "The Mask of Zorro",
  "The Masseuse",
  "Masterminds",
  "The Match Factory Girl",
  "Matilda",
  "The Matrix",
  "Maverick",
  "Maximum Risk",
  "Meet Joe Black",
  "Memoirs of an Invisible Man",
  "Memphis Belle",
  "Men in Black",
  "Men in White",
  "Merlin",
  "Mermaids",
  "The Messenger: The Story of Joan of Arc",
  "Metropolitan",
  "Mickey Blue Eyes",
  "Mighty Aphrodite",
  "The Mighty Ducks",
  "Mighty Joe Young",
  "Mighty Morphin Power Rangers: The Movie",
  "Milk Money",
  "Mimic",
  "Misery",
  "Mission: Impossible",
  "Mixed Nuts",
  "Mo' Better Blues",
  "The Mod Squad",
  "Money Talks",
  "Money Train",
  "Monkey Trouble",
  "Mortal Kombat series:",
  "Mortal Kombat",
  "Mortal Kombat: Annihilation",
  "Mr. Holland's Opus",
  "Mr. Magoo",
  "Mrs. Doubtfire",
  "Mrs. Winterbourne",
  "Much Ado About Nothing",
  "Mulan",
  "Mulholland Falls",
  "The Mummy",
  "Muppets from Space",
  "Muppet Treasure Island",
  "Muriel's Wedding",
  "Music of the Heart",
  "My Best Fiend",
  "My Best Friend's Wedding",
  "My Blue Heaven",
  "My Cousin Vinny",
  "My Favorite Martian",
  "My Favorite Season",
  "My Giant",
  "My Girl",
  "My Girl 2",
  "My Own Private Idaho",
  "My Summer Story",
  "Myself in the Distant Future",
  "Mystery Science Theater 3000: The Movie",
  "The Naked Gun 2½: The Smell of Fear",
  "Naked Gun 33⅓: The Final Insult",
  "Naked Lunch",
  "National Lampoon's Loaded Weapon 1",
  "National Lampoon's Vegas Vacation",
  "Natural Born Killers",
  "Nell",
  "The Net",
  "Never Been Kissed",
  "Neverending Story series:",
  "The NeverEnding Story II: The Next Chapter",
  "The NeverEnding Story III",
  "Never Talk to Strangers",
  "New Jack City",
  "Newsies",
  "The Newton Boys",
  "The Next Karate Kid",
  "Nick of Time",
  "A Night at the Roxbury",
  "Nightbreed",
  "The Nightmare Before Christmas",
  "Nixon",
  "Noises Off",
  "North",
  "Not Without My Daughter",
  "Nothing But Trouble",
  "Notting Hill",
  "Now and Then",
  "Nurse Nancy",
  "The Nutty Professor",
  "Office Space",
  "The Omega Code",
  "On Deadly Ground",
  "Once Upon a Crime",
  "One False Move",
  "Operation Dumbo Drop",
  "Orgazmo",
  "Othello",
  "Other People's Money",
  "The Other Sister",
  "Out for Justice",
  "Outbreak",
  "Pacific Heights",
  "The Pagemaster",
  "Panther",
  "Paprika",
  "The Parent Trap",
  "Passenger 57",
  "Passport to Paris",
  "Patch Adams",
  "Patriot Games",
  "Paulie",
  "PCU",
  "The Pebble and the Penguin",
  "Pecker",
  "The Pelican Brief",
  "The People Under the Stairs",
  "The People vs. Larry Flynt",
  "A Perfect World",
  "Pet Shop",
  "Phantoms",
  "Philadelphia",
  "The Piano",
  "Piranha",
  "Pinocchio",
  "The Player",
  "Playing By Heart",
  "Playing the Odds",
  "Pleasantville",
  "Pocahontas",
  "Pocahontas II: Journey to a New World",
  "Poetic Justice",
  "Point Break",
  "Point of No Return",
  "Poison",
  "Poison Ivy",
  "Poison Ivy II: Lily",
  "Poison Ivy: The New Seduction",
  "Pokémon: The First Movie",
  "Posse",
  "Postcards from the Edge",
  "The Postman",
  "Predator 2",
  "Presumed Innocent",
  "Pretty Woman",
  "Primary Colors",
  "The Prince of Egypt",
  "The Prince of Tides",
  "Private Parts",
  "Problem Child series:",
  "Problem Child",
  "Problem Child 2",
  "Problem Child 3: Junior in Love",
  "Léon: The Professional",
  "Psycho",
  "Psycho IV: The Beginning",
  "Pulp Fiction",
  "Pump Up the Volume",
  "Puppet Master II",
  "Puppet Master III: Toulon's Revenge",
  "Puppet Master 4",
  "Puppet Master 5: The Final Chapter",
  "Pure Country",
  "Pushing Tin",
  "Q&A",
  "Quest for Camelot",
  "The Quick and the Dead",
  "Quick Change",
  "Quicksilver Highway",
  "Quigley Down Under",
  "Quiz Show",
  "Rambling Rose",
  "Random Hearts",
  "Ravenous",
  "Reality Bites",
  "Red Rock West",
  "The Red Violin",
  "Regarding Henry",
  "Regeneration",
  "The Remains of the Day",
  "Renaissance Man",
  "The Rescuers Down Under",
  "Reservoir Dogs",
  "Retro Puppet Master",
  "Return of the Living Dead 3",
  "Return to the Blue Lagoon",
  "Reversal of Fortune",
  "Richard III",
  "Ri¢hie Ri¢h",
  "Richie Rich's Christmas Wish",
  "Ride with the Devil",
  "Ringu",
  "A River Runs Through It",
  "Rob Roy",
  "Robin Hood: Men in Tights",
  "Robin Hood: Prince of Thieves",
  "RoboCop 2",
  "RoboCop 3",
  "Robot Jox",
  "The Rock",
  "Rock-A-Doodle",
  "The Rocketeer",
  "RocketMan",
  "Rocky V",
  "Romance",
  "Romeo + Juliet",
  "Romy and Michele's High School Reunion",
  "Rosencrantz & Guildenstern Are Dead",
  "Rounders",
  "Rover Dangerfield",
  "Rubin and Ed",
  "Rudy",
  "The Rugrats Movie",
  "Run Lola Run",
  "Runaway Bride",
  "Rush Hour",
  "Rushmore",
  "The Russia House",
  "Sabrina",
  "The Saint",
  "A Saintly Switch",
  "The Sandlot",
  "The Santa Clause",
  "Sarafina!",
  "Sátántangó",
  "Saving Private Ryan",
  "The Scarlet Letter",
  "A Scene at the Sea",
  "Scent of a Woman",
  "Schindler's List",
  "School Ties",
  "Scream",
  "Scream 2",
  "Screamers",
  "The Secret Garden",
  "The Secret of NIMH 2: Timmy to the Rescue",
  "Selena",
  "Senior Trip",
  "Sense and Sensibility",
  "Serial Mom",
  "Set It Off",
  "Seven",
  "Seven Years in Tibet",
  "Sgt. Kabukiman N.Y.P.D.",
  "The Shadow",
  "Shadowlands",
  "Shakespeare in Love",
  "Shakes the Clown",
  "Shattered",
  "The Shawshank Redemption",
  "She's All That",
  "Shining Through",
  "Shreck",
  "The Shrimp on the Barbie",
  "Short Cuts",
  "Showgirls",
  "Side Out",
  "The Siege",
  "The Silence of the Lambs",
  "Simon Birch",
  "A Simple Plan",
  "A Simple Twist of Fate",
  "Sinbad",
  "Single White Female",
  "Singles",
  "Sirens",
  "Six Days Seven Nights",
  "Six Degrees of Separation",
  "The Sixth Sense",
  "Slacker",
  "Slam Dunk Ernest",
  "SLC Punk!",
  "Sleeping with the Enemy",
  "Sleepless in Seattle",
  "Sleepy Hollow",
  "Sliding Doors",
  "Sling Blade",
  "Sliver",
  "Small Soldiers",
  "A Smile Like Yours",
  "Snow Falling on Cedars",
  "So I Married an Axe Murderer",
  "Soapdish",
  "Solar Crisis",
  "Son in Law",
  "South Park: Bigger, Longer & Uncut",
  "Spaced Invaders",
  "Space Jam",
  "Spawn",
  "The Specialist",
  "Species",
  "Species II",
  "Speechless",
  "Speed",
  "Speed 2: Cruise Control",
  "Sphere",
  "Spiceworld",
  "Spy Hard",
  "Stalingrad",
  "Star Trek: First Contact",
  "Star Trek: Generations",
  "Star Trek: Insurrection",
  "Star Trek VI: The Undiscovered Country",
  "Star Wars: Episode I - The Phantom Menace",
  "Stargate",
  "Stay Tuned",
  "Steel",
  "Stella",
  "The Stendhal Syndrome",
  "Stepmom",
  "Still Crazy",
  "Stop! or My Mom Will Shoot",
  "The Story of Us",
  "Strange Days",
  "A Stranger Among Us",
  "Street Fighter",
  "Striptease",
  "Stuart Little",
  "The Stupids",
  "subUrbia",
  "Sudden Death",
  "Summer of Sam",
  "Sunset Grill",
  "Sunshine",
  "Super Mario Bros.",
  "The Suspended Step of the Stork",
  "The Swan Princess series",
  "The Swan Princess",
  "The Swan Princess II: Escape from Castle Mountain",
  "The Swan Princess: The Mystery of the Enchanted Kingdom",
  "Switch",
  "Switched at Birth",
  "Switching Goals",
  "Swoon",
  "The Talented Mr. Ripley",
  "Tales of Erotica",
  "Tall Tale",
  "The Tango Lesson",
  "Tank Girl",
  "Tarzan",
  "A Taste of Cherry",
  "Tatie Danielle",
  "Teaching Mrs. Tingle",
  "Teenage Catgirls in Heat",
  "Teenage Mutant Ninja Turtles series:",
  "Teenage Mutant Ninja Turtles",
  "Teenage Mutant Ninja Turtles II: The Secret of the Ooze",
  "Teenage Mutant Ninja Turtles III",
  "Tekken",
  "The Temp",
  "Terminator 2: Judgment Day",
  "Terror Firmer",
  "Tesis",
  "Texasville",
  "That Darn Cat",
  "Thelma and Louise",
  "Theodore Rex",
  "The Theory of Flight",
  "There's Something About Mary",
  "A Thin Line Between Love and Hate",
  "The Thin Red Line",
  "This Boy's Life",
  "The Thomas Crown Affair",
  "The Tie That Binds",
  "Three Colors: Blue",
  "Three Colors: Red",
  "Three Colors: White",
  "The Spitfire Grill",
  "The Three Musketeers",
  "The Three Musketeers",
  "Threesome",
  "Thumbelina",
  "Thumbelina",
  "Thursday",
  "Tilaï",
  "A Time to Kill",
  "Timecop",
  "Titanic",
  "Tom and Huck",
  "Tom and Jerry: The Movie",
  "Tombstone",
  "Tommy Boy",
  "Tomorrow Never Dies",
  "Toothless",
  "Top of the World",
  "Topsy-Turvy",
  "Total Recall",
  "To Die For",
  "To Grandmother's House We Go",
  "To Wong Foo, Thanks for Everything! Julie Newmar",
  "Toy Soldiers",
  "Toy Story",
  "Toy Story 2",
  "Toys",
  "Trainspotting",
  "Treasure Island",
  "Tremors",
  "Tremors 2: Aftershocks",
  "Trojan War",
  "Troll 2",
  "Troll 3",
  "A Troll in Central Park",
  "Tromeo and Juliet",
  "True Colors",
  "True Lies",
  "True Romance",
  "The Truman Show",
  "The Truth About Cats and Dogs",
  "Truth or Dare",
  "Tumbleweeds",
  "Turbo: A Power Rangers Movie",
  "The Tune",
  "Turbulence",
  "Twelfth Night: Or What You Will",
  "Twelve Monkeys",
  "Twin Peaks: Fire Walk With Me",
  "Twister",
  "Two Much",
  "The Horseman Show",
  "Ulysses' Gaze",
  "Under Siege",
  "Under Siege 2: Dark Territory",
  "Unforgiven",
  "Unlawful Entry",
  "Untamed Heart",
  "Until the End of the World",
  "The Usual Suspects",
  "Vampire in Brooklyn",
  "Very Bad Things",
  "Vegas In Space",
  "Vegas Vacation",
  "Vendetta",
  "Vincent & Theo",
  "The Virgin Suicides",
  "Virtual Sexuality",
  "Virus",
  "Volcano",
  "La Vie sexuelle des Belges 1950-1978",
  "Waiting to Exhale",
  "Waking Ned",
  "A Walk in the Clouds",
  "War of the Buttons",
  "Warriors of Virtue",
  "Wayne's World series:",
  "Wayne's World",
  "Wayne's World 2",
  "The Waterboy",
  "Waterworld",
  "The Wedding Singer",
  "Weekend at Bernie's II",
  "We're Back! A Dinosaur's Story",
  "What About Bob?",
  "What's Eating Gilbert Grape",
  "What's Love Got to Do with It",
  "Where Angels Fear to Tread",
  "While You Were Sleeping",
  "Whispering Corridors",
  "Whispers in the Dark",
  "White Men Can't Jump",
  "White Sands",
  "Who Am I?",
  "Why Not Me?",
  "Wide Sargasso Sea",
  "Wild America",
  "Wild at Heart",
  "Wild Orchid",
  "Wild Things",
  "Wild Wild West",
  "Wing Commander",
  "The Wings of the Dove",
  "The Witches",
  "Wolf",
  "The World Is Not Enough",
  "World's Biggest Gang Bang",
  "Wrongfully Accused",
  "Wyatt Earp",
  "The X Files: Fight the Future",
  "Yellow Hair",
  "You've Got Mail",
  "Young Guns II",
  "Zazel"
];

}());